// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tribe.Data;

#nullable disable

namespace Tribe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250815101735_creator")]
    partial class creator
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CreatorPlan", b =>
                {
                    b.Property<string>("Guid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateEvents")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateRaffles")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUploadDigitalContent")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUseWindowsApp")
                        .HasColumnType("bit");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HaveShopItems")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenMenge")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("CreatorPlans");

                    b.HasData(
                        new
                        {
                            Guid = "basic-plan-guid-001",
                            Aktiv = true,
                            CanCreateEvents = true,
                            CanCreateRaffles = true,
                            CanUploadDigitalContent = true,
                            CanUseWindowsApp = true,
                            FeaturesJson = "{\"maxProjects\":1,\"support\":\"email\"}",
                            HaveShopItems = true,
                            Name = "Basic Plan",
                            TokenMenge = 10000
                        },
                        new
                        {
                            Guid = "pro-plan-guid-002",
                            Aktiv = true,
                            CanCreateEvents = true,
                            CanCreateRaffles = true,
                            CanUploadDigitalContent = true,
                            CanUseWindowsApp = true,
                            FeaturesJson = "{\"maxProjects\":10,\"support\":\"priority\"}",
                            HaveShopItems = true,
                            Name = "Pro Plan",
                            TokenMenge = 50000
                        });
                });

            modelBuilder.Entity("CreatorPlanPricing", b =>
                {
                    b.Property<string>("Guid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatorPlanGuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValueEuro")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ValueGbPound")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ValueUSD")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Guid");

                    b.HasIndex("CreatorPlanGuid");

                    b.ToTable("CreatorPlanPricings");

                    b.HasData(
                        new
                        {
                            Guid = "basic-plan-guid-001-monthly",
                            CreatorPlanGuid = "basic-plan-guid-001",
                            Duration = "Monthly",
                            ValueEuro = 8.99m,
                            ValueGbPound = 7.99m,
                            ValueUSD = 9.99m
                        },
                        new
                        {
                            Guid = "basic-plan-guid-001-annual",
                            CreatorPlanGuid = "basic-plan-guid-001",
                            Duration = "Annual",
                            ValueEuro = 89.99m,
                            ValueGbPound = 79.99m,
                            ValueUSD = 99.99m
                        },
                        new
                        {
                            Guid = "pro-plan-guid-002-monthly",
                            CreatorPlanGuid = "pro-plan-guid-002",
                            Duration = "Monthly",
                            ValueEuro = 26.99m,
                            ValueGbPound = 23.99m,
                            ValueUSD = 29.99m
                        },
                        new
                        {
                            Guid = "pro-plan-guid-002-annual",
                            CreatorPlanGuid = "pro-plan-guid-002",
                            Duration = "Annual",
                            ValueEuro = 269.99m,
                            ValueGbPound = 239.99m,
                            ValueUSD = 299.99m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.AffiliatePartner", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatorProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PartneName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerLogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorProfileId");

                    b.ToTable("AffiliatePartner");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVATPayer")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LegalForm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaypalPayerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PrivacyPolicyAccepted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PrivacyPolicyAcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShopifyToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateOrRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeAccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TermsAccepted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TermsAcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VATId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.CreatorPlacement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatorProfileId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlacementLogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacementName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacementUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebHookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorProfileId");

                    b.ToTable("CreatorPlacement");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.CreatorPlan", b =>
                {
                    b.Property<string>("Guid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateEvents")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateRaffles")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUploadDigitalContent")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUseWindowsApp")
                        .HasColumnType("bit");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HaveShopItems")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenMenge")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("CreatorPlan");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.CreatorPlanPricing", b =>
                {
                    b.Property<string>("Guid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatorPlanGuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValueEuro")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ValueGbPound")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ValueUSD")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Guid");

                    b.HasIndex("CreatorPlanGuid");

                    b.ToTable("CreatorPlanPricing");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.CreatorSubscription", b =>
                {
                    b.Property<string>("Guid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorPlanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatorPlanPricingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TribeProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Guid");

                    b.HasIndex("CreatorPlanId");

                    b.HasIndex("CreatorPlanPricingId");

                    b.HasIndex("TribeProfileId")
                        .IsUnique();

                    b.ToTable("CreatorSubscription");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.CreatorToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CirculatingSupply")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TokenSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TotalSupply")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorProfileId", "TokenName")
                        .IsUnique();

                    b.ToTable("CreatorTokens");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.ProfileFollow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatorProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FollowedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FollowerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorProfileId");

                    b.HasIndex("FollowerId", "CreatorProfileId")
                        .IsUnique();

                    b.ToTable("ProfileFollows", t =>
                        {
                            t.HasCheckConstraint("CK_ProfileFollow_NotSelf", "[FollowerId] <> [CreatorProfileId]");
                        });
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.ProfileTokenHolding", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("CreatorTokenId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorTokenId");

                    b.HasIndex("ProfileId", "CreatorTokenId")
                        .IsUnique();

                    b.ToTable("ProfileTokenHoldings", t =>
                        {
                            t.HasCheckConstraint("CK_TokenHolding_PositiveAmount", "[Amount] >= 0");
                        });
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.Raffle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentEntries")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DrawnAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxEntries")
                        .HasColumnType("int");

                    b.Property<int>("PrizeCount")
                        .HasColumnType("int");

                    b.Property<string>("PrizeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrizeValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RaffleConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaffleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorProfileId");

                    b.ToTable("Raffles", t =>
                        {
                            t.HasCheckConstraint("CK_Raffle_ValidDateRange", "[EndDate] > [StartDate]");
                        });
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.RaffleEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntryCount")
                        .HasColumnType("int");

                    b.Property<string>("EntryNumbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("QualifiedForNextStage")
                        .HasColumnType("bit");

                    b.Property<string>("RaffleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TokensSpent")
                        .HasColumnType("int");

                    b.Property<string>("UsedTokenId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("RaffleId");

                    b.HasIndex("UsedTokenId");

                    b.ToTable("RaffleEntries", t =>
                        {
                            t.HasCheckConstraint("CK_RaffleEntry_PositiveCount", "[EntryCount] > 0");

                            t.HasCheckConstraint("CK_RaffleEntry_PositiveTokens", "[TokensSpent] >= 0");
                        });
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.RaffleTokenRequirement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorTokenId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<string>("RaffleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RequiredAmount")
                        .HasColumnType("int");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorTokenId");

                    b.HasIndex("RaffleId", "CreatorTokenId")
                        .IsUnique()
                        .HasFilter("[CreatorTokenId] IS NOT NULL");

                    b.ToTable("RaffleTokenRequirements", t =>
                        {
                            t.HasCheckConstraint("CK_RaffleTokenReq_PositiveAmount", "[RequiredAmount] >= 0");
                        });
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.RaffleWinner", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DrawnAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<bool>("PrizeClaimed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PrizeClaimedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrizeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrizeValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RaffleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WinningNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntryId")
                        .IsUnique();

                    b.HasIndex("ProfileId");

                    b.HasIndex("RaffleId");

                    b.ToTable("RaffleWinners", t =>
                        {
                            t.HasCheckConstraint("CK_RaffleWinner_PositivePosition", "[Position] > 0");
                        });
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.TribeProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsCreator")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("DisplayName");

                    b.ToTable("TribeProfiles");

                    b.HasDiscriminator().HasValue("TribeProfile");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.CreatorProfile", b =>
                {
                    b.HasBaseType("Tribe.Bib.Models.TribeRelated.TribeProfile");

                    b.Property<bool>("AcceptingCollaborations")
                        .HasColumnType("bit");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollaborationInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatorName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiscordUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FollowerCount")
                        .HasColumnType("int");

                    b.Property<string>("ImageTemplateUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatreonUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TikTokUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRaffles")
                        .HasColumnType("int");

                    b.Property<int>("TotalTokensDistributed")
                        .HasColumnType("int");

                    b.Property<string>("TwitchUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VerifiedCreator")
                        .HasColumnType("bit");

                    b.Property<string>("YouTubeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CreatorName")
                        .IsUnique()
                        .HasFilter("[CreatorName] IS NOT NULL");

                    b.HasDiscriminator().HasValue("CreatorProfile");
                });

            modelBuilder.Entity("CreatorPlanPricing", b =>
                {
                    b.HasOne("CreatorPlan", "CreatorPlan")
                        .WithMany("PricingList")
                        .HasForeignKey("CreatorPlanGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorPlan");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Tribe.Bib.Models.TribeRelated.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Tribe.Bib.Models.TribeRelated.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tribe.Bib.Models.TribeRelated.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Tribe.Bib.Models.TribeRelated.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.AffiliatePartner", b =>
                {
                    b.HasOne("Tribe.Bib.Models.TribeRelated.CreatorProfile", "Creator")
                        .WithMany("AffiliatePartners")
                        .HasForeignKey("CreatorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.CreatorPlacement", b =>
                {
                    b.HasOne("Tribe.Bib.Models.TribeRelated.CreatorProfile", "Creator")
                        .WithMany("Placements")
                        .HasForeignKey("CreatorProfileId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.CreatorPlanPricing", b =>
                {
                    b.HasOne("Tribe.Bib.Models.TribeRelated.CreatorPlan", "CreatorPlan")
                        .WithMany("PricingList")
                        .HasForeignKey("CreatorPlanGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorPlan");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.CreatorSubscription", b =>
                {
                    b.HasOne("Tribe.Bib.Models.TribeRelated.CreatorPlan", "CreatorPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CreatorPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tribe.Bib.Models.TribeRelated.CreatorPlanPricing", "CreatorPlanPricing")
                        .WithMany()
                        .HasForeignKey("CreatorPlanPricingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tribe.Bib.Models.TribeRelated.TribeProfile", "TribeProfile")
                        .WithOne("ActiveCreatorSubscription")
                        .HasForeignKey("Tribe.Bib.Models.TribeRelated.CreatorSubscription", "TribeProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorPlan");

                    b.Navigation("CreatorPlanPricing");

                    b.Navigation("TribeProfile");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.CreatorToken", b =>
                {
                    b.HasOne("Tribe.Bib.Models.TribeRelated.CreatorProfile", "Creator")
                        .WithMany("CreatorTokens")
                        .HasForeignKey("CreatorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.ProfileFollow", b =>
                {
                    b.HasOne("Tribe.Bib.Models.TribeRelated.CreatorProfile", "Followed")
                        .WithMany()
                        .HasForeignKey("CreatorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tribe.Bib.Models.TribeRelated.TribeProfile", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Followed");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.ProfileTokenHolding", b =>
                {
                    b.HasOne("Tribe.Bib.Models.TribeRelated.CreatorToken", "Token")
                        .WithMany()
                        .HasForeignKey("CreatorTokenId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Tribe.Bib.Models.TribeRelated.TribeProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.Raffle", b =>
                {
                    b.HasOne("Tribe.Bib.Models.TribeRelated.CreatorProfile", "Creator")
                        .WithMany("Raffles")
                        .HasForeignKey("CreatorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.RaffleEntry", b =>
                {
                    b.HasOne("Tribe.Bib.Models.TribeRelated.TribeProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Tribe.Bib.Models.TribeRelated.Raffle", "Raffle")
                        .WithMany()
                        .HasForeignKey("RaffleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Tribe.Bib.Models.TribeRelated.CreatorToken", "UsedToken")
                        .WithMany()
                        .HasForeignKey("UsedTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Profile");

                    b.Navigation("Raffle");

                    b.Navigation("UsedToken");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.RaffleTokenRequirement", b =>
                {
                    b.HasOne("Tribe.Bib.Models.TribeRelated.CreatorToken", "CreatorToken")
                        .WithMany()
                        .HasForeignKey("CreatorTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tribe.Bib.Models.TribeRelated.Raffle", "Raffle")
                        .WithMany()
                        .HasForeignKey("RaffleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatorToken");

                    b.Navigation("Raffle");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.RaffleWinner", b =>
                {
                    b.HasOne("Tribe.Bib.Models.TribeRelated.RaffleEntry", "Entry")
                        .WithOne()
                        .HasForeignKey("Tribe.Bib.Models.TribeRelated.RaffleWinner", "EntryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Tribe.Bib.Models.TribeRelated.TribeProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Tribe.Bib.Models.TribeRelated.Raffle", "Raffle")
                        .WithMany()
                        .HasForeignKey("RaffleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Profile");

                    b.Navigation("Raffle");
                });

            modelBuilder.Entity("CreatorPlan", b =>
                {
                    b.Navigation("PricingList");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.CreatorPlan", b =>
                {
                    b.Navigation("PricingList");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.TribeProfile", b =>
                {
                    b.Navigation("ActiveCreatorSubscription");
                });

            modelBuilder.Entity("Tribe.Bib.Models.TribeRelated.CreatorProfile", b =>
                {
                    b.Navigation("AffiliatePartners");

                    b.Navigation("CreatorTokens");

                    b.Navigation("Placements");

                    b.Navigation("Raffles");
                });
#pragma warning restore 612, 618
        }
    }
}
