// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tribe.Data;

#nullable disable

namespace Tribe.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20260207214356_AddEventTicketOnlineFields")]
    partial class AddEventTicketOnlineFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tribe.Bib.ShopRelated.ShopStruckture+ProductReview", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVerifiedPurchase")
                        .HasColumnType("bit");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_ProductReviews_ProductId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ProductReviews_UserId");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("Tribe.Bib.ShopRelated.ShopStruckture+ShopCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorProfileId")
                        .HasDatabaseName("IX_ShopCategories_CreatorProfileId");

                    b.ToTable("ShopCategories");
                });

            modelBuilder.Entity("Tribe.Bib.ShopRelated.ShopStruckture+ShopOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShippingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatorProfileId")
                        .HasDatabaseName("IX_ShopOrders_CreatorProfileId");

                    b.HasIndex("CustomerUserId")
                        .HasDatabaseName("IX_ShopOrders_CustomerUserId");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_ShopOrders_OrderNumber");

                    b.ToTable("ShopOrders");
                });

            modelBuilder.Entity("Tribe.Bib.ShopRelated.ShopStruckture+ShopOrderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("BookedSlot")
                        .HasColumnType("datetime2");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DownloadExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("DownloadToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxDownloads")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_ShopOrderItems_OrderId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_ShopOrderItems_ProductId");

                    b.ToTable("ShopOrderItems");
                });

            modelBuilder.Entity("Tribe.Bib.ShopRelated.ShopStruckture+ShopProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PurchaseCount")
                        .HasColumnType("int");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ShopProducts_CreatedAt");

                    b.HasIndex("CreatorProfileId")
                        .HasDatabaseName("IX_ShopProducts_CreatorProfileId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ShopProducts_Status");

                    b.ToTable("ShopProducts", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Tribe.Bib.ShopRelated.ShopStruckture+EventTicketProduct", b =>
                {
                    b.HasBaseType("Tribe.Bib.ShopRelated.ShopStruckture+ShopProduct");

                    b.Property<string>("DressCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("EventAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EventEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Includes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IncludesDrinks")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludesFood")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnlineEvent")
                        .HasColumnType("bit");

                    b.Property<int>("MaxTickets")
                        .HasColumnType("int");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RefundDeadline")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RefundableUntil")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresIdentification")
                        .HasColumnType("bit");

                    b.Property<int>("SoldTickets")
                        .HasColumnType("int");

                    b.Property<string>("StreamUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("EventTicketProducts", (string)null);
                });

            modelBuilder.Entity("Tribe.Bib.ShopRelated.ShopStruckture+ImageProduct", b =>
                {
                    b.HasBaseType("Tribe.Bib.ShopRelated.ShopStruckture+ShopProduct");

                    b.Property<DateTime?>("DownloadExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("HighResImageUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPhotoSet")
                        .HasColumnType("bit");

                    b.Property<int>("MaxDownloads")
                        .HasColumnType("int");

                    b.Property<int>("PhotoCount")
                        .HasColumnType("int");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipDownloadUrl")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ImageProducts", (string)null);
                });

            modelBuilder.Entity("Tribe.Bib.ShopRelated.ShopStruckture+PhysicalProduct", b =>
                {
                    b.HasBaseType("Tribe.Bib.ShopRelated.ShopStruckture+ShopProduct");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimatedDeliveryDays")
                        .HasColumnType("int");

                    b.Property<bool>("FreeShippingOver")
                        .HasColumnType("bit");

                    b.Property<decimal>("FreeShippingThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingCountries")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("TrackInventory")
                        .HasColumnType("bit");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasIndex("SKU")
                        .IsUnique()
                        .HasDatabaseName("IX_PhysicalProducts_SKU")
                        .HasFilter("[SKU] IS NOT NULL");

                    b.ToTable("PhysicalProducts", (string)null);
                });

            modelBuilder.Entity("Tribe.Bib.ShopRelated.ShopStruckture+ServiceProduct", b =>
                {
                    b.HasBaseType("Tribe.Bib.ShopRelated.ShopStruckture+ShopProduct");

                    b.Property<bool>("AllowRescheduling")
                        .HasColumnType("bit");

                    b.Property<string>("AvailableSlots")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MaxAdvanceBookingDays")
                        .HasColumnType("int");

                    b.Property<int>("MaxBookingsPerDay")
                        .HasColumnType("int");

                    b.Property<string>("MeetingInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinAdvanceBookingHours")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresBooking")
                        .HasColumnType("bit");

                    b.Property<int>("RescheduleHoursLimit")
                        .HasColumnType("int");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ServiceProducts", (string)null);
                });

            modelBuilder.Entity("Tribe.Bib.ShopRelated.ShopStruckture+VideoProduct", b =>
                {
                    b.HasBaseType("Tribe.Bib.ShopRelated.ShopStruckture+ShopProduct");

                    b.Property<bool>("AllowDownload")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DownloadExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("HasSubtitles")
                        .HasColumnType("bit");

                    b.Property<int>("MaxDownloads")
                        .HasColumnType("int");

                    b.Property<string>("PreviewVideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubtitleLanguages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoQuality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("VideoProducts", (string)null);
                });

            modelBuilder.Entity("Tribe.Bib.ShopRelated.ShopStruckture+ShopOrderItem", b =>
                {
                    b.HasOne("Tribe.Bib.ShopRelated.ShopStruckture+ShopOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tribe.Bib.ShopRelated.ShopStruckture+EventTicketProduct", b =>
                {
                    b.HasOne("Tribe.Bib.ShopRelated.ShopStruckture+ShopProduct", null)
                        .WithOne()
                        .HasForeignKey("Tribe.Bib.ShopRelated.ShopStruckture+EventTicketProduct", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tribe.Bib.ShopRelated.ShopStruckture+ImageProduct", b =>
                {
                    b.HasOne("Tribe.Bib.ShopRelated.ShopStruckture+ShopProduct", null)
                        .WithOne()
                        .HasForeignKey("Tribe.Bib.ShopRelated.ShopStruckture+ImageProduct", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tribe.Bib.ShopRelated.ShopStruckture+PhysicalProduct", b =>
                {
                    b.HasOne("Tribe.Bib.ShopRelated.ShopStruckture+ShopProduct", null)
                        .WithOne()
                        .HasForeignKey("Tribe.Bib.ShopRelated.ShopStruckture+PhysicalProduct", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tribe.Bib.ShopRelated.ShopStruckture+ServiceProduct", b =>
                {
                    b.HasOne("Tribe.Bib.ShopRelated.ShopStruckture+ShopProduct", null)
                        .WithOne()
                        .HasForeignKey("Tribe.Bib.ShopRelated.ShopStruckture+ServiceProduct", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tribe.Bib.ShopRelated.ShopStruckture+VideoProduct", b =>
                {
                    b.HasOne("Tribe.Bib.ShopRelated.ShopStruckture+ShopProduct", null)
                        .WithOne()
                        .HasForeignKey("Tribe.Bib.ShopRelated.ShopStruckture+VideoProduct", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
